FROM node:22-alpine

WORKDIR /usr/src/app

RUN npm install -g pnpm

COPY pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./tsconfig.json ./tsconfig.json
COPY ./package.json ./package.json

COPY ./apps/client ./apps/client

RUN pnpm install
RUN pnpm run build

EXPOSE 4173

CMD ["pnpm", "start"]