FROM node:22-alpine

WORKDIR /usr/src/app

RUN npm install -g pnpm

COPY pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY ./packages ./packages
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./tsconfig.json ./tsconfig.json
COPY ./package.json ./package.json

COPY ./apps/server ./apps/server

RUN pnpm install
RUN pnpm run db:generate
RUN pnpm run build

EXPOSE 3000

CMD ["pnpm", "start"]